### ISSUE TITLE
glitchtip-web not starting

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [ruanbekker/docker-glitchtip-traefik#1]
I tried to use your docker-compose file, but actually the web won't start.
The log output just states some warnings, but I don't see any suitable error.

Any idea what could be wrong? When did you last test the docker-compose?

**Comment by ruanbekker** [comment]
I noticed that im using `latest` tags which is not ideal. Let me look into it tonight.

**Comment by mariomurrent-softwaresolutions** [comment]
Ah i see. Thx 😊

**Comment by ruanbekker** [comment]
Commit https://github.com/ruanbekker/docker-glitchtip-traefik/commit/71ee52b55749c7b1dee115af8b13b65993c02e1c should resolve it

**Comment by mariomurrent-softwaresolutions** [comment]
I’ll try it out today. Thank you very much

**Comment by mariomurrent-softwaresolutions** [comment]
It's at least starting, but I guess I have some configuration errors because I'm getting a 404 not found from Traefik.
But this is probably an error on my side.

Thanks for fixing the docker compose.
